### ISSUE TITLE
尝试更换成medium时提示显存不足

### ISSUE THREAD

**Issue by sihulj** [rerender2021/heard#9]
在使用whisper、whisper desktop或者buzz等软件时用的也是medium模型，可以正常使用。
报错内容如下：

whisper server started
great! use gpu
use model: medium.pt
restart whisper server process
try to init vosk asr engine
asrDir exists, start asr server D:\Softwares\heard-v1.0.1\whisper-gpu-server
start whisper server with model:  medium.pt
whisper server exit: 1
stdout: 2023-04-08 11:17:36.529  INFO : Whisper API is starting, please wait...

stdout: torch info:
1.13.1+cu117
11.7

stdout: True

stdout: 2023-04-08 11:17:44.967 ERROR : CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.46 GiB already allocated; 0 bytes free; 3.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    Traceback (most recent call last):
      File "main.py", line 45, in <module>
      File "whisper\__init__.py", line 154, in load_model
        return model.to(device)
stdout:
      File "torch\nn\modules\module.py", line 989, in to
        return self._apply(convert)
      File "torch\nn\modules\module.py", line 641, in _apply
        module._apply(fn)
      File "torch\nn\modules\module.py", line 641, in _apply
        module._apply(fn)
      File "torch\nn\modules\module.py", line 641, in _apply
        module._apply(fn)
      [Previous line repeated 2 more times]
      File "torch\nn\modules\module.py", line 664, in _apply
        param_applied = fn(param)
      File "torch\nn\modules\module.py", line 987, in convert
        return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.46 GiB already allocated; 0 bytes free; 3.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by rerender2021** [comment]
是的，这个问题是显存不足。

whisper desktop或者buzz可以正常运行的原因可能是

- buzz使用的是cpu
- whisper desktop（我猜你指的是[https://github.com/Const-me/Whisper](https://github.com/Const-me/Whisper)）是whisper的另一种实现，显存占用更小一些。
- whisper不确定你指的什么，我封装的是openai的python版https://github.com/openai/whisper

我也会遇到这个问题：电脑上16G内存，跑large模型也跑不起来，只能使用medium的。

**Comment by rerender2021** [comment]
它官方有个内存占用图：

![image](https://user-images.githubusercontent.com/87927336/230748152-e9b151c0-3ed6-457e-8676-9fd8fb5c5ec6.png)

> https://github.com/openai/whisper

**Comment by sihulj** [comment]
ok明白了，谢谢，那我还是看看用small来试试。
使用的的确是https://github.com/Const-me/Whisper。

**Comment by rerender2021** [comment]
> ok明白了，谢谢，那我还是看看用small来试试。 使用的的确是[https://github.com/Const-me/Whisper。](https://github.com/Const-me/Whisper%E3%80%82)

不客气~
